version: '3.8'
services:
  stress-testing-demo:
    container_name: stress-testing-demo
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/products?allowPublicKeyRetrieval=true
    depends_on:
        - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: mysql:8.2.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: products
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
