INSERT INTO product (name, category) VALUES ('Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Hair Gel','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Oil','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Mask','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Mousse','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Wax','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Pomade','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Color Dye','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Extensions','Hair Extensions');
INSERT INTO product (name, category) VALUES ('Hair Straightener','Hair Styling Tools');
INSERT INTO product (name, category) VALUES ('Hair Curler','Hair Styling Tools');
INSERT INTO product (name, category) VALUES ('Hair Dryer','Hair Styling Tools');
INSERT INTO product (name, category) VALUES ('Leave-In Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Dandruff Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Frizz Control Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Thickening Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Curl Enhancing Cream','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Volumizing Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Heat Protectant Spray','Hair Styling Tools');
INSERT INTO product (name, category) VALUES ('Hair Repair Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Hair Repair Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Texturizing Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Root Lifter','Styling Product');
INSERT INTO product (name, category) VALUES ('Coconut Oil for Hair','Treatment');
INSERT INTO product (name, category) VALUES ('Anti-Frizz Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Anti-Frizz Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Argan Oil Hair Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Curl Defining Gel','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Detangler','Conditioner');
INSERT INTO product (name, category) VALUES ('Dry Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Hair Styling Cream','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Setting Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Keratin Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Keratin Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Hair Lotion','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Revitalizing Mask','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Growth Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Detox Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Hair Detox Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Hydrating Hair Mask','Treatment');
INSERT INTO product (name, category) VALUES ('Leave-In Hair Mask','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Revitalizing Oil','Treatment');
INSERT INTO product (name, category) VALUES ('Scalp Scrub Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Hair Thickening Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Beard Oil','Beard Care');
INSERT INTO product (name, category) VALUES ('Beard Balm','Beard Care');
INSERT INTO product (name, category) VALUES ('Beard Wash','Beard Care');
INSERT INTO product (name, category) VALUES ('Hair Paste','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Powder','Styling Product');
INSERT INTO product (name, category) VALUES ('Heat Protectant Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Growth Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Hair Growth Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Hair Spray Gel','Styling Product');
INSERT INTO product (name, category) VALUES ('Leave-In Hair Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Curl Enhancing Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Curling Wand','Hair Styling Tools');
INSERT INTO product (name, category) VALUES ('Hair Straightening Brush','Hair Styling Tools');
INSERT INTO product (name, category) VALUES ('Curling Iron','Hair Styling Tools');
INSERT INTO product (name, category) VALUES ('Hair Volumizing Mousse','Styling Product');
INSERT INTO product (name, category) VALUES ('Texturizing Hair Powder','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Clay','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Sculpting Wax','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Setting Lotion','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Curl Enhancer','Styling Product');
INSERT INTO product (name, category) VALUES ('Dry Scalp Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Hair Detox Mask','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Thickening Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Coconut Hair Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Beard Wash and Conditioner','Beard Care');
INSERT INTO product (name, category) VALUES ('Beard Grooming Kit','Beard Care');
INSERT INTO product (name, category) VALUES ('Beard Comb','Beard Care');
INSERT INTO product (name, category) VALUES ('Hair Texturizing Paste','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Volumizing Powder','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Frizz Control Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Shine Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Clarifying Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Hydrating Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Deep Conditioning Mask','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Thickening Shampoo and Conditioner Set','Shampoo and Conditioner');
INSERT INTO product (name, category) VALUES ('Curl-Defining Cream','Styling Product');
INSERT INTO product (name, category) VALUES ('Heat Protectant Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Repair Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Gloss Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Volume Boosting Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Volume Boosting Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Hair Building Fibers','Treatment');
INSERT INTO product (name, category) VALUES ('Smoothing Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Smoothing Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Hair Detox Scrub','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Growth Oil','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Color Protecting Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Hair Color Protecting Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Hair Color Protecting Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Curl-Enhancing Lotion','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Curl-Enhancing Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Curl-Defining Mousse','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Taming Cream','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Serum for Frizz Control','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Serum for Shine','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Serum for Repair','Treatment');
INSERT INTO product (name, category) VALUES ('Anti-Dandruff Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Anti-Dandruff Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Anti-Dandruff Scalp Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Thickening Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Thickening Lotion','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Thickening Powder','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Thickening Foam','Styling Product');
INSERT INTO product (name, category) VALUES ('Hair Thickening Hairspray','Styling Product');
INSERT INTO product (name, category) VALUES ('Split End Repair Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Leave-In Hair Detangler','Conditioner');
INSERT INTO product (name, category) VALUES ('Leave-In Hair Repair Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Growth Shampoo and Conditioner Set','Shampoo and Conditioner');
INSERT INTO product (name, category) VALUES ('Hair Growth Spray','Styling Product');
INSERT INTO product (name, category) VALUES ('Clarifying Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Hydrating Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Sulfate-Free Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Sulfate-Free Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Natural Hair Mask','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Loss Shampoo','Shampoo');
INSERT INTO product (name, category) VALUES ('Hair Loss Conditioner','Conditioner');
INSERT INTO product (name, category) VALUES ('Hair Loss Treatment Serum','Treatment');
INSERT INTO product (name, category) VALUES ('Protein Hair Mask','Treatment');
INSERT INTO product (name, category) VALUES ('Moisturizing Hair Mask','Treatment');
INSERT INTO product (name, category) VALUES ('Hair Color Remover','Color Remover');
INSERT INTO product (name, category) VALUES ('Temporary Hair Color Spray','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Tint','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Chalk','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Bleach','Color Bleach');
INSERT INTO product (name, category) VALUES ('Hair Color Developer','Hair Color Developer');
INSERT INTO product (name, category) VALUES ('Hair Color Brush','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Mixing Bowl','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Dye Applicator Brush','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Dye Kit','Hair Color Kit');
INSERT INTO product (name, category) VALUES ('Hair Color Gloves','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Cape','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Apron','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Bowl and Brush Set','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Removal Wipes','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Stain Remover','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Permanent Hair Color Kit','Hair Color Kit');
INSERT INTO product (name, category) VALUES ('Semi-Permanent Hair Color','Hair Color');
INSERT INTO product (name, category) VALUES ('Demi-Permanent Hair Color','Hair Color');
INSERT INTO product (name, category) VALUES ('Temporary Hair Color Gel','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Spray','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Chalk','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Wax','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Markers','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Cream','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Powder','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Paste','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Pomade','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Stick','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Mascara','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Pens','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Pencils','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Crayons','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Spray Paint','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Highlights','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Streaks','Hair Color');
INSERT INTO product (name, category) VALUES ('Hair Color Ombre Kit','Hair Color Kit');
INSERT INTO product (name, category) VALUES ('Hair Color Balayage Kit','Hair Color Kit');
INSERT INTO product (name, category) VALUES ('Hair Color Foils','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Caps','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Brushes','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Clips','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Combs','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Foil Dispenser','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Mixing Brush','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Brushes','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Bowls','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Caps','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Clips','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Combs','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Foils','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Sponges','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Trays','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Wraps','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Aprons','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Gloves','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Neck Strips','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Shower Capes','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Collar Papers','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Bibs','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Viewing Window','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Snaps','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Velcro','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Elastic','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Adjustable Closure','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Cape Clips','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Snap Buttons','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Hook and Loop Closure','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Buckle','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Drawstring','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Tie Closure','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Zipper','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Magnets','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Collar','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Pockets','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Lining','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Velcro Neck Strips','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Snap Buttons Neck Strips','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Hook and Loop Closure Neck Strips','Hair Color Accessories');
INSERT INTO product (name, category) VALUES ('Hair Color Tint Capes with Adjustable Closure Neck Strips','Hair Color Accessories');